### ISSUE TITLE
Crash when saving a preset

### ISSUE THREAD

**Issue by TBlazeWarriorT** [leduyquang753/HUDToggler#6]
**Name:** Crash when saving a preset

**Summary:** Mod crashed when trying to save a preset

**Details:** I downloaded the mod, changed a few settings and clicked Save preset then the game crashed
[crash-2019-09-26_01.23.17-client.txt](https://github.com/leduyquang753/HUDToggler/files/3655885/crash-2019-09-26_01.23.17-client.txt)

**Comment by leduyquang753** [comment]
Fixed. See release 1.4.0.4.

Sorry for taking too long, my laptop was stolen. This is from a new one.
