### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by TBlazeWarriorT** [leduyquang753/HUDToggler#7]
Hi, I hope the mod is still getting updated! I just downloaded the mod and was trying to set it up in a comfortable way that I like, but I failed to do a few things.
Basically I'd like to know if it's possible to move things around, I don't want my ping display on a huge font on the bottom left, I'd like to move it to the top left of the screen and make it smaller.
Also, for the armor HUD, I'd like it on the bottom left, displaying as a percentage but without decimals, and there doesn't seem to be settings for those. Also I don't like the bow arrows left displayed in my crosshair, I'd like to be able to move them to the corner of the screen.
Lastly, I'd want to know if it's possible to show the player's (and maybe other players too above their heads when you look at them) damage reduction or effective HP in 1.8.9 ([which has a simpler armor formula](https://minecraft.gamepedia.com/Armor/Before_1.9)), no mod seems to do that, would be great if I found one that does.

**Comment by TBlazeWarriorT** [comment]
Found an alternative to most of those issues, implementing optional

**Comment by leduyquang753** [comment]
About the HUD elements movement feature, I think I will decide to write a brand new mod for it, with an interactive HUD editor. However I am kinda unsure of how many people will actually use it, so that my efforts won't be literally wasted. I think I will make a poll on the forums for this.

**Comment by TBlazeWarriorT** [comment]
@leduyquang753 Yes, I think I agree with you. 5zig currently has too many more features, so it's preferred for displaying FPS and such things. Your mod is still great for other things though, like the low health vignette.
